### ISSUE TITLE
How to Set Username/Password?

### ISSUE THREAD

**Issue by invictus2010** [geudrik/peloton-api#11]
Running this in a Jupyter Notebook on macOS. I've set up environmental variables up as PELOTON_USERNAME and PELOTON_PASSWORD.

When I attempt to run some of the functions in the library, I get told `name 'PELOTON_USERNAME' is not defined` However, I ran `%env` which verified my environmental variables were set. So I'm not sure the reason for the error.

Where exactly does my config file need to go if I just wanted to set it there?

**Comment by geudrik** [comment]
Odd that you're seeing issues using the env vars... I'll h ave to see if I can reproduce. Can you describe how you're invoking python and your usecase?

The fallback though is to create a file `~/.config/peloton` and add the following to it

```
[peloton]
username = you@email.com
password = your password
```

**Comment by geudrik** [comment]
@invictus2010 I can't reproduce this. If you can paste a stacktrace that'd be helpful
