### ISSUE TITLE
Can you point me to how to install this package?

### ISSUE THREAD

**Issue by smg000** [geudrik/peloton-api#5]
I'm so sorry, but I don't know how to install this (pip3 install...). Can you point me to resources that might help me?

**Comment by geudrik** [comment]
Google would be a good place to start... That question has many complete answers, dependent on, namely, the environment you're working in. 

This is a code library - if you're not a coder, this package will be of little use to you.

**Comment by Whatapalaver** [comment]
`pip install peloton` is the general gist.
I'm using this with a jupyter notebook and used the following code block:
```
import sys
!{sys.executable} -m pip install peloton
```
I find this post helpful for notebook installation https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/
