### ISSUE TITLE
Attribute Errors

### ISSUE THREAD

**Issue by rivkahcarl** [geudrik/peloton-api#6]
While using the library, I have come across a number of Attribute errors on some of the objects.

`AttributeError: 'PelotonRide' object has no attribute 'instructor'`
`AttributeError: 'PelotonWorkoutMetrics' object has no attribute 'calories_summary'`

Is anyone familiar with why this is not consistent?

**Comment by t-lynch** [comment]
The JSON data returned from the Peloton API sometimes doesn't contain certain data.   For example, on a "Scenic Ride", there is no one leading the class, so there is no "instructor" field set in the data.    The library doesn't set attributes for values that don't exist in the data.

You can work around this in your own code by checking for the existence of the attribute before using it like this:
```
if hasattr(my_ride, 'instructor'): 
    print(my_ride.instructor)
else:
    print('no instructor')
```

You could also wrap the code in a try/catch and then handle the error (or ignore it)
```
try:
    print(my_ride.instructor)
except AttributeError:
    print('no instructor')
```

Or you can use getattr to use a default value when it's not defined
```
print(getattr(my_ride, 'instructor', 'no instructor')
```

**Comment by rivkahcarl** [comment]
Perfect, thanks! 
I had wrapped these errors in a try/catch but thought there might be a more graceful way to handle the missing fields.
